### ISSUE TITLE
About using dataloaders

### ISSUE THREAD

**Issue by kockok** [gabivlj/chat-it-api#2]
Hello, I can see that you are writing dataloaders in this app.
However, I was told that mongodb won't produce N+1 problem.
So, I am just wondering why we still need to write dataloaders when using NOsql.

**Comment by gabivlj** [comment]
We don’t want multiple queries to mongodb when we can do a single one.

**Comment by kockok** [comment]
> We don’t want multiple queries to mongodb when we can do a single one.

Just to clarify, is it the fact that graphql is causing the "n+1" problem even though the db is mongodb. However, some say mongodb won't have "n+1" problem, what's the point for that?
Thanks

**Comment by gabivlj** [comment]
The problem will be present because when you want for example a post with comments inside, you will make a query for each post, and we don’t want that, that will happen in Mongo, Postgresql, any DB... There is dataloader because we don’t want to make a lot of mongo queries, just make a single one and gather all the data we need.

**Comment by gabivlj** [comment]
> > We don’t want multiple queries to mongodb when we can do a single one.
> 
> Just to clarify, is it the fact that graphql is causing the "n+1" problem even though the db is mongodb. However, some say mongodb won't have "n+1" problem, what's the point for that?
> Thanks

Can you link the people that say that? Maybe they do another method for batching inside the same request , but the way that it works without dataloader is that it will call the resolvers and make a lot of database lookups.

**Comment by kockok** [comment]
> > > We don’t want multiple queries to mongodb when we can do a single one.
> > 
> > 
> > Just to clarify, is it the fact that graphql is causing the "n+1" problem even though the db is mongodb. However, some say mongodb won't have "n+1" problem, what's the point for that?
> > Thanks
> 
> Can you link the people that say that? Maybe they do another method for batching inside the same request , but the way that it works without dataloader is that it will call the resolvers and make a lot of database lookups.

I'm thrilled by your reply.
I asked a similar question on stackoverflow and got downvotes.
![Screenshot 2020-06-29 at 12 41 25 AM](https://user-images.githubusercontent.com/232541/85953265-b07bd480-b9a1-11ea-9c27-0ba9cb2e4a2d.png)

And recently got baffled by the relationship between the n+1 thing and nosql.

**Comment by gabivlj** [comment]
Basically, if you have a relationship between collections and you wanna add data from another collection you might encounter a n+1 problem when using Graphql and gathering data the way I said before. That usually happens in every db that can have this kind of relationship, but it’s more common to see it in relational ones because they are more effective doing join operations and things like that.

**Comment by kockok** [comment]
> Basically, if you have a relationship between collections and you wanna add data from another collection you might encounter a n+1 problem when using Graphql and gathering data the way I said before. That usually happens in every db that can have this kind of relationship, but it’s more common to see it in relational ones because they are more effective doing join operations and things like that.

Thank you so much for your thorough reply indeed.
