### ISSUE TITLE
gqlgen generate problem

### ISSUE THREAD

**Issue by kockok** [gabivlj/chat-it-api#3]
In the generated `models_gen.go` file,
you added methods like:
```
func (e TypeOfMessage) IsValid() bool {
	switch e {
	case TypeOfMessageConnection, TypeOfMessageMessage, TypeOfMessageExit:
		return true
	}
	return false
}
```

However, gqlgen noted `DO NOT EDIT`.

So, my question is that why you add those methods there?
If you were to regenerate the schema, will those code be wiped out?

**Comment by gabivlj** [comment]
Gqlgen generated that method for me, I did not create it.

**Comment by kockok** [comment]
Oh I see, they should be generated for the `enum`.

For the domain part, is that you write the models and then specify in the `gqlgen.yml` or you specify first in `gqlgen.yml` and then gqlgen will generate the code for you?

Same for the resolvers, are the resolvers generated separately or you code to fit gqlgen?

**Comment by gabivlj** [comment]
The resolvers are generated by gqlgen, the domain part I specify in the yml of gqlgen that it should take the schema from there, and I also specify that it must create resolvers.

For example in post.go:
https://github.com/gabivlj/chat-it-app/blob/3331568af2ed98febe82c3eee2c0c09cfba7448a/internals/domain/post.go#L1-L11
 and the gqlgen.yml
https://github.com/gabivlj/chat-it-app/blob/3331568af2ed98febe82c3eee2c0c09cfba7448a/gqlgen.yml#L64-L70

As you can see I tell gqlgen that it can find the schema of Post there and that it doesn't need to generate the code for me. I also tell gqlgen that it should generate resolvers for User and Messages because I wanna be able to get the user of a post or the messages of a post when I get a post. 

I also make sure that in the schema.graphql these fields exist as they are named in gqlgen.yml

https://github.com/gabivlj/chat-it-app/blob/3331568af2ed98febe82c3eee2c0c09cfba7448a/schema/schema.graphql#L12-L21

**Comment by kockok** [comment]
Thanks for the reply, it would definitely be a BIG help for the gqlgen newbies.

**Comment by kockok** [comment]
> The resolvers are generated by gqlgen, the domain part I specify in the yml of gqlgen that it should take the schema from there, and I also specify that it must create resolvers.
> 
> For example in post.go:
> 
> https://github.com/gabivlj/chat-it-app/blob/3331568af2ed98febe82c3eee2c0c09cfba7448a/internals/domain/post.go#L1-L11
> 
> 
> and the gqlgen.yml
> https://github.com/gabivlj/chat-it-app/blob/3331568af2ed98febe82c3eee2c0c09cfba7448a/gqlgen.yml#L64-L70
> 
> As you can see I tell gqlgen that it can find the schema of Post there and that it doesn't need to generate the code for me. I also tell gqlgen that it should generate resolvers for User and Messages because I wanna be able to get the user of a post or the messages of a post when I get a post.
> 
> I also make sure that in the schema.graphql these fields exist as they are named in gqlgen.yml
> 
> https://github.com/gabivlj/chat-it-app/blob/3331568af2ed98febe82c3eee2c0c09cfba7448a/schema/schema.graphql#L12-L21

Hello, you defined the `chat` field in the schema, however I can see that you use `messages` field in the gqlgen.yml. Why's that?

**Comment by gabivlj** [comment]
Damn, that's definitely a mistake haha 😅. It should be called chat as well.
